### ISSUE TITLE
Qbittorrent plugin fails to open torrent list

### ISSUE THREAD

**Issue by tjwoosta** [Hiltronix/repo#1]
Kodi 17, Win 8.1 x64

`22:33:07.232 T:7964   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2026' in position 27: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\tj\AppData\Roaming\Kodi\addons\plugin.program.qbittorrent\default.py", line 173, in <module>
                                                list.menu(handle=sys.argv[1], filter=settings.torrent_filter[torrent_filter_preselect])
                                              File "C:\Users\tj\AppData\Roaming\Kodi\addons\plugin.program.qbittorrent\resources\lib\list.py", line 81, in menu
                                                addDirectory(handle, name, title, auth_token, hash, state, progress, size, dlspeed, upspeed, seeds, leechers, eta, filter, category, thumbnail_path, fanart_path, total_items, context_menu_items)
                                              File "C:\Users\tj\AppData\Roaming\Kodi\addons\plugin.program.qbittorrent\resources\lib\list.py", line 102, in addDirectory
                                                meta['plot'] = '[COLOR gold]{}[/COLOR][CR][COLOR cyan]Status:[/COLOR] {}[CR][COLOR cyan]Size:[/COLOR] {}[CR][COLOR cyan]Done:[/COLOR] {}  [COLOR cyan]ETA:[/COLOR] {}[CR][COLOR cyan]Down:[/COLOR] {}  [COLOR cyan]Up:[/COLOR]{}[CR][COLOR cyan]Seeders:[/COLOR] {}  [COLOR cyan]Leechers:[/COLOR] {}[CR][COLOR cyan]Filter:[/COLOR] {}[CR][COLOR cyan]Label Category:[/COLOR] {}'.format(name[:30]+'...', state, size, progress, eta, dlspeed, upspeed, seeds, leechers, filter, category)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 27: ordinal not in range(128)
                                            -->End of Python script error report<--
22:33:07.289 T:7808   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.program.qbittorrent/?mode=2&name=Torrent%20List&url
22:33:07.289 T:7808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.qbittorrent/?mode=2&name=Torrent%20List&url) failed`

**Comment by Hiltronix** [comment]
What version of qbittorrent addon you are using?  In the qBittorrent addon select Settings > About.

**Comment by tjwoosta** [comment]
The addon is version 2.1.6

Qbittorrent itself is version 4.1.1

**Comment by Hiltronix** [comment]
The error appears to be due to displaying a unicode non standard ASCII character.  Basically anything that's not a normal English character.  I though I had allowed for this already, but have to take a further look.

Did this error occur during a search?  If so, you can provide the search text you are/were searching for when the result occurred?  That way I can reproduce this error and test while I fix it.  

This project is on my free time, so it may take me a view days to get around to fixing it, so bare with me.  I'll push out an update once I can reproduce the error, and fix it.  Thanks.

**Comment by tjwoosta** [comment]
The error occurs when I open the plugin, then choose "Torrent List".

I guess that means there must be a unicode character in one of the torrents names? I don't see anything unusual but in case it helps here is the list
https://pastebin.com/rLGNSajd

**Comment by Hiltronix** [comment]
Thanks for your patience.  I believe I have solved the problem in v.2.1.7, which is now available in my repo.

The issue was due to a unicode character called Horizontal Ellipsis (U+2026) which is a character that looks like 3 periods in a row, "…".  This is why it was difficult for you, or I, to notice in the Pastebin list you shared with me.  It's a character in the string:

The Chainsmokers - Memories… Do Not Open (2017) [24bit]

I could reproduce the error with the search "chainsmokers memories" and category "all" and using the zoogle search engine.  In case you want test it yourself.

Please let me know if you still have a problem.
Thanks for bringing it to my attention.

**Comment by tjwoosta** [comment]
Nice, it works great now. Thank you!
